version: "3"

services:
  meetup_postgres:
    container_name: Meetup_Postgres
    image: postgres:14.5
    env_file: .env
    ports:
      - 5556:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MeetingDB" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - .\\volumes\\postgres-data\\:/var/lib/postgresql/data

  meetup_migrator:
    container_name: Meetup_Migrator
    build:
      context: ./../
      dockerfile: ./src/Meetup.Migrator/Dockerfile
    env_file: .env
    healthcheck:
            test: [ "CMD-SHELL", "echo", "1" ]
            interval: 1s
            timeout: 1s
            retries: 5
    depends_on:
      meetup_postgres:
        condition: service_healthy

  meetup_api:
    container_name: Meetup_API
    build:
      context: ./../
      dockerfile: ./src/Meetup.Api/Dockerfile
    env_file: .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      meetup_migrator:
        condition: service_completed_successfully
      meetup_postgres:
        condition: service_healthy